[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_API_URL = "https://your-site-name.netlify.app" 